/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        secondary: '#3c6929',
        tertiary: '#785900',
        primary: '#a04100',
        background: '#faf9f6',
        surface: '#faf9f6',
        'surface-bright': '#faf9f6',
        'surface-dim': '#dbdad7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f1',
        'surface-container': '#efeeeb',
        'surface-container-high': '#e9e8e5',
        'surface-container-highest': '#e3e2e0',
        'surface-variant': '#e3e2e0',
        'surface-tint': '#a04100',
        outline: '#887364',
        'outline-variant': '#dbc2b0',
        'on-background': '#1a1c1a',
        'on-surface': '#1a1c1a',
        'on-surface-variant': '#554336',
        'inverse-surface': '#2f312f',
        'inverse-on-surface': '#f2f1ee',
        'inverse-primary': '#ffb693',
        'primary-container': '#ff9762',
        'on-primary-container': '#762e00',
        'primary-fixed': '#ffdbcc',
        'primary-fixed-dim': '#ffb693',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#351000',
        'on-primary-fixed-variant': '#7a3000',
        'secondary-container': '#bcf1a1',
        'secondary-fixed': '#bcf1a1',
        'secondary-fixed-dim': '#a1d488',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#426f2f',
        'on-secondary-fixed': '#052100',
        'on-secondary-fixed-variant': '#255013',
        'tertiary-container': '#e0a900',
        'tertiary-fixed': '#ffdf9e',
        'tertiary-fixed-dim': '#fabd00',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#584000',
        'on-tertiary-fixed': '#261a00',
        'on-tertiary-fixed-variant': '#5b4300',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['var(--font-headline)', 'serif'],
        body: ['var(--font-body)', 'sans-serif'],
        label: ['var(--font-body)', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      maxWidth: {
        'screen-2xl': '1536px',
      },
      boxShadow: {
        soft: '0 24px 80px -32px rgba(26, 28, 26, 0.18)',
      },
    },
  },
  plugins: [],
};
