/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        secondary: '#4c6a34',
        tertiary: '#9a6a00',
        primary: '#8f350f',
        background: '#f7efe3',
        surface: '#f8f1e8',
        'surface-bright': '#fff8ef',
        'surface-dim': '#e8cfb7',
        'surface-container-lowest': '#fffaf4',
        'surface-container-low': '#f6eadc',
        'surface-container': '#f1dfc8',
        'surface-container-high': '#ead4bc',
        'surface-container-highest': '#e1c3a4',
        'surface-variant': '#dbc3ab',
        'surface-tint': '#8f350f',
        outline: '#8a664c',
        'outline-variant': '#d9b794',
        'on-background': '#1a1c1a',
        'on-surface': '#1a1c1a',
        'on-surface-variant': '#664733',
        'inverse-surface': '#2f312f',
        'inverse-on-surface': '#f2f1ee',
        'inverse-primary': '#f3b37f',
        'primary-container': '#ffb07c',
        'on-primary-container': '#6f2507',
        'primary-fixed': '#ffd9c1',
        'primary-fixed-dim': '#f2b37e',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#351000',
        'on-primary-fixed-variant': '#7d2f0f',
        'secondary-container': '#c9e7b3',
        'secondary-fixed': '#c9e7b3',
        'secondary-fixed-dim': '#a7cb8b',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#335526',
        'on-secondary-fixed': '#052100',
        'on-secondary-fixed-variant': '#2a5514',
        'tertiary-container': '#f0c566',
        'tertiary-fixed': '#ffe3ac',
        'tertiary-fixed-dim': '#e3b24b',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#5d4300',
        'on-tertiary-fixed': '#261a00',
        'on-tertiary-fixed-variant': '#6a4d06',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['var(--font-headline)', 'serif'],
        body: ['var(--font-body)', 'sans-serif'],
        label: ['var(--font-body)', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      maxWidth: {
        'screen-2xl': '1536px',
      },
      boxShadow: {
        soft: '0 24px 80px -32px rgba(26, 28, 26, 0.18)',
      },
    },
  },
  plugins: [],
};

export default config;
